name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      # আপনি যদি অন্য কোনো ব্রাঞ্চে পুশ করেন, তবে সেটিও এখানে যুক্ত করতে পারেন
  workflow_dispatch:

# ডেপ্লয়মেন্টের জন্য পারমিশন সেট করা
permissions:
  contents: read
  pages: write
  id-token: write

# একাধিক ডেপ্লয়মেন্ট হলে একে অপরকে ক্যান্সেল করার জন্য
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      
      # যেহেতু আপনার প্রজেক্টে কোনো বিল্ড টুল (যেমন npm run build) নেই, 
      # তাই আমরা সরাসরি পুরো ফোল্ডারটি আপলোড করে দেব
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' 
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4            "server": {
              "androidScheme": "https",
              "hostname": "localhost",
              "cleartext": true
            }
          }
          EOF
         
          npx cap add android || true
          npx cap sync android
      - name: Build Android APK
        run: |
          cd android
         
         
          echo "configurations.all {
              resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                  if (details.requested.group == 'org.jetbrains.kotlin') {
                      details.useVersion '1.8.22'
                  }
              }
          }" >> app/build.gradle
         
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mobile-App-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
